### ISSUE TITLE
Update GitHub Actions

### ISSUE THREAD

**Issue by Hunter275** [meshtastic/js#105]
Update GitHub actions now that the repo is getting more attention.

This will change a lot as I learn more about GitHub Actions. 
*If you'd like to lend a hand please comment.*

TODO:
- [x] Update version to match protobuf versions
- [ ] Create an Action to update protobufs automatically and release a new version
  - [ ] BONUS: Update protobuf's Actions to fire off this Action or subscribe to protobuf releases somehow 
- [ ] Don't allow updates to .github files to update Actions and run without approval (SECURITY)
- [ ] Ensure the version is bumped when merging to `master`
- [X] Only publish to NPM and JSR when a release is created

**Comment by Hunter275** [comment]
https://github.com/nektos/act

**Comment by Hunter275** [comment]
Update version to match protobufs version https://github.com/meshtastic/protobufs/

**Comment by Hunter275** [comment]
Notes from @thebentern 

Workflow_dispatch adds a button to "Run Workflow" and allows you to select a branch from Actions to run the workflow on.

Then use `if: ${{ github.event_name == 'workflow_dispatch' }}` to gate jobs

**Comment by Hunter275** [comment]
The "version check" job needs to run when a PR is created with the target branch of `master`, it currently does not.

**Comment by Hunter275** [comment]
I'm not sure if this just isn't an issue because I'm a meshtastic org member but I am able to modify the Actions and they run on the PR with the updated .yml files, thats a huge red flag to me and we need to protect ourselves on our other repos.
